export const AUCTION_ERROR = "AUCTION_ERROR";

export const GET_AUCTIONS_REQUEST = "GET_AUCTIONS_REQUEST";
export const GET_AUCTIONS_RESPONSE = "GET_AUCTIONS_RESPONSE";
export const GET_AUCTIONS_ERROR = "GET_AUCTIONS_ERROR";

export const CREATE_AUCTIONS_REQUEST = "CREATE_AUCTIONS_REQUEST";
export const CREATE_AUCTIONS_RESPONSE = "CREATE_AUCTIONS_RESPONSE";
export const CREATE_AUCTIONS_ERROR = "CREATE_AUCTIONS_ERROR";

export const PLACE_BID_REQUEST = "PLACE_BID_REQUEST";
export const PLACE_BID_RESPONSE = "PLACE_BID_RESPONSE";
export const PLACE_BID_ERROR = "PLACE_BID_ERROR";

export const SET_BIDDING_ON = "SET_BIDDING_ON";

export const RESET_BIDDING_ON = "RESET_BIDDING_ON";

export const SET_BID_AMOUNT = "SET_BID_AMOUNT";

export const SET_TOKEN = "SET_TOKEN";

export const SET_CLAIMS = "SET CLAIMS";

export const DISPLAY_SPINNER = "DISPLAY_SPINNER";
